### ISSUE TITLE
[BUG] Failed to load resource

### ISSUE THREAD

**Issue by waahah** [Xdy1579883916/vanilla-pudding#7]
> *Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR*

```
Refused to load the script 'blob' 
because it violates the following Content Security Policy directive: "script-src github.githubassets.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
***
```
TypeError: Failed to fetch dynamically imported module: blob:
```

**Comment by Xdy1579883916** [comment]
Is there a detailed case?

**Comment by Xdy1579883916** [comment]
It seems that we need to change

```
// @world MAIN
```

to

```
// @world USER_SCRIPT
```

**Comment by Xdy1579883916** [comment]
If you don't need esm to load external resources, you can also use


```
// @name new-script
// @runAt document_idle
// @allFrames false
// @world MAIN
// @runWith raw
// @match https://github.com/Xdy1579883916/vanilla-pudding/issues/7

// see doc: https://github.com/Xdy1579883916/vanilla-pudding?tab=readme-ov-file#matadata
console.log(1)
```

**Comment by waahah** [comment]
```js
// @name github_star
// @runAt document_idle
// @allFrames false
// @world MAIN
// @runWith esm
// @match *://github.com/*
// @match *://www.eggvod.cn/

// ==UserScript==
import * as $ from 'https://unpkg.com/jquery@3.7.1'
(function () {
    'use strict';
    var $ = $ || window.$;
    $(document).empty();
})();
```

**Comment by Xdy1579883916** [comment]
If you only operate DOM, you can modify the code like this


```js
// @name github_star
// @runAt document_idle
// @allFrames false
// @world USER_SCRIPT
// @runWith esm
// @match *://github.com/*
// @match *://www.eggvod.cn/

// ==UserScript==
import 'https://unpkg.com/jquery@3.7.1'
(function () {
  console.log("jquery", $)
  $("body").html( "empty..." )
})();

```

**Comment by Xdy1579883916** [comment]
Case 2:

If you want to inject code into the main world, you may not be able to load external js (if CSP restricts it). You can copy the code of the external library completely into the current script.

```diff

// @name github_star
// @runAt document_idle
// @allFrames false
-// @world USER_SCRIPT
-// @runWith esm
+// @world MAIN
+// @runWith raw
// @match *://github.com/*
// @match *://www.eggvod.cn/

-import 'https://unpkg.com/jquery@3.7.1'
// code from  https://unpkg.com/jquery@3.7.1/dist/jquery.min.js
+!function(e,t){"use strict";....................................."undefined"==typeof e&&(C.jQuery=C.$=S),S});

// your code
(function () {
  console.log("jquery", $)
  $("body").html( "empty..." )
})();

```

**Comment by waahah** [comment]
> 案例 2：
> 
> 如果你想将代码注入到主世界，你可能无法加载外部 js（如果 CSP 限制它）。您可以将外部库的代码完全复制到当前脚本中。
> 
> ```diff
> // @name github_star
> // @runAt document_idle
> // @allFrames false
> -// @world USER_SCRIPT
> -// @runWith esm
> +// @world MAIN
> +// @runWith raw
> // @match *://github.com/*
> // @match *://www.eggvod.cn/
> 
> -import 'https://unpkg.com/jquery@3.7.1'
> // code from  https://unpkg.com/jquery@3.7.1/dist/jquery.min.js
> +!function(e,t){"use strict";....................................."undefined"==typeof e&&(C.jQuery=C.$=S),S});
> 
> // your code
> (function () {
>   console.log("jquery", $)
>   $("body").html( "empty..." )
> })();
> ```

> Tampermonkey brings in the CDN to perform the above MAIN environment injection and no problem

**Comment by Xdy1579883916** [comment]
Yes, our execution mechanism is different. If you cannot complete the development with this extension, it is recommended that you choose Tampermonkey because you don't need to change anything for your code.
